include ~/.cache/wal/colors-kitty.conf

foreground #4c4f69
background #eff1f5

font_family      Monolisa
font_size        11

window_padding_width 5 10 5 10
cursor_shape block
shell_integration no-cursor

inactive_border_color #6C7086
bell_border_color #F9E2AF
background_opacity 1

hide_window_decorations true

allow_remote_control yes
listen_on unix:/tmp/mykitty
