active_border_color #FAA031
cursor #FAA031
url_color #FAA031

selection_foreground #ffffff
selection_background #FAA031

active_tab_foreground #ffffff
active_tab_background #FAA031
inactive_tab_foreground #6c6f85
inactive_tab_background #eff1f5
