[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#ff0000
KWinPalette\activeBlend=#ff0000
KWinPalette\activeForeground=#232629
KWinPalette\activeTitleBtnBg=#f8f8f8
KWinPalette\frame=#f8f8f8
KWinPalette\inactiveBackground=#eff0f1
KWinPalette\inactiveBlend=#eff0f1
KWinPalette\inactiveForeground=#232629
KWinPalette\inactiveFrame=#f8f8f8
KWinPalette\inactiveTitleBtnBg=#f8f8f8
Palette\active=#232629, #f8f8f8, #dedede, #ececec, #d0d0d0, #dedede, #232629, #ffffff, #232629, #ffffff, #f8f8f8, #b7b7b7, #e7868f, #232629, #5d0000, #9b59b6, #f7f7f7, #000000, #f8f8f8, #232629, #707d8a, #e7868f
Palette\disabled=#a5a6a7, #ececec, #ffffff, #f4f4f4, #8b8b8b, #c5c5c5, #aaabac, #ffffff, #a5a6a7, #f3f3f3, #ececec, #494949, #ececec, #a5a6a7, #c19d9d, #d6bae1, #ebebeb, #000000, #f8f8f8, #232629, #c2c8ce, #ececec
Palette\inactive=#232629, #f8f8f8, #dedede, #ececec, #d0d0d0, #dedede, #232629, #ffffff, #232629, #ffffff, #f8f8f8, #b7b7b7, #f6dbde, #232629, #5d0000, #9b59b6, #f7f7f7, #000000, #f8f8f8, #232629, #707d8a, #f6dbde
font="MonoLisaCode,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
