# Catppuccin Latte — btop theme

theme[main_bg]="#eff1f5"
theme[main_fg]="#4c4f69"

theme[title]="#4c4f69"
theme[hi_fg]="#7287fd"

theme[selected_bg]="#ccd0da"
theme[selected_fg]="#7287fd"

theme[inactive_fg]="#9ca0b0"
theme[graph_text]="#dc8a78"

theme[meter_bg]="#ccd0da"
theme[proc_misc]="#dc8a78"

theme[cpu_box]="#8839ef"     # Mauve
theme[mem_box]="#40a02b"     # Green
theme[net_box]="#e64553"     # Maroon/Red
theme[proc_box]="#1e66f5"    # Blue

theme[div_line]="#acb0be"

theme[temp_start]="#40a02b"
theme[temp_mid]="#df8e1d"
theme[temp_end]="#d20f39"

theme[cpu_start]="#179299"
theme[cpu_mid]="#04a5e5"
theme[cpu_end]="#7287fd"

theme[free_start]="#8839ef"
theme[free_mid]="#7287fd"
theme[free_end]="#1e66f5"

theme[cached_start]="#209fb5"
theme[cached_mid]="#1e66f5"
theme[cached_end]="#7287fd"

theme[available_start]="#fe640b"
theme[available_mid]="#e64553"
theme[available_end]="#d20f39"

theme[used_start]="#40a02b"
theme[used_mid]="#179299"
theme[used_end]="#04a5e5"

theme[download_start]="#fe640b"
theme[download_mid]="#e64553"
theme[download_end]="#d20f39"

theme[upload_start]="#40a02b"
theme[upload_mid]="#179299"
theme[upload_end]="#04a5e5"

theme[process_start]="#209fb5"
theme[process_mid]="#7287fd"
theme[process_end]="#8839ef"
